### ISSUE TITLE
DNA Vaccination by Electroporation Amplifies Broadly Cross-Restricted Public TCR Clonotypes Shared with HIV Controllers

### ISSUE THREAD

**Issue by mikessh** [antigenomics/vdjdb-db#225]
http://www.jimmunol.org/content/early/2017/10/07/jimmunol.1700953

**Comment by RenskeVroomans** [comment]
I'm almost done putting the data in the table. One issue: they use primers for only a few V genes, and therefore the sequence frequencies in the table are frequencies per tetramer **and** per primer, not just per tetramer. I could correct for this by summing the frequencies of the primers, but it would still be quite different since only a few primers are used while there are ample clones with different V genes (see e.g. figure 2 B). What shall I do about this?

**Comment by mikessh** [comment]
Its impossible to give right frequencies if one don't knows the exact V usage numbers in that case, I agree with you. The best thing we can do is to put frequencies as is, and write a ``comment`` for all records that frequency is provided for tet+primer.

**Comment by mikessh** [comment]
The method.identification says ``antigen-loaded-targets`` and the method.verification is ``tetramer-stain`` - this already means that frequencies are not that meaningful, the data is nicely validated. So now I see no problem at all!
